version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/bradgignac/fortune-api
    steps:
      - checkout
      - run: env
      - run: go get github.com/golang/dep/cmd/dep
      - run: make deps
      - run: make build
